pos1-posmode       =kinematic
pos1-frequency     =l1+l2
pos1-soltype       =forward
pos1-elmask        =15
pos1-dynamics      =off
pos1-tidecorr      =off
pos1-ionoopt       =brdc
pos1-tropopt       =saas
pos1-sateph        =brdc
pos1-navsys        =31
pos2-armode        =fix-and-hold
pos2-arthres       =3.0
pos2-arminfix      =10
pos2-gloarmode     =on
pos2-galarmode     =on
pos2-bdsarmode     =on
pos2-slipthres     =0.05
out-solformat      =llh
out-outhead        =on
out-outopt         =on
out-timesys        =gpst
out-timeform       =hms
out-timendec       =3
out-degform        =deg
out-height         =ellipsoidal
out-outstat        =residual
ant1-postype       =llh
ant1-pos1          =0
ant1-pos2          =0
ant1-pos3          =0
ant2-postype       =xyz
ant2-pos1          =2078167.0251
ant2-pos2          =-5683987.2712
ant2-pos3          =2006702.5967
misc-timeinterp    =on
